# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rpc/echo/v1/echo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rpc/echo/v1/echo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16rpc/echo/v1/echo.proto\x12\x07\x65\x63ho.v1\"M\n\nEchoRecord\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\"$\n\x11\x43reateEchoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"9\n\x12\x43reateEchoResponse\x12#\n\x06record\x18\x01 \x01(\x0b\x32\x13.echo.v1.EchoRecord\"\x1c\n\x0eGetEchoRequest\x12\n\n\x02id\x18\x01 \x01(\t\"6\n\x0fGetEchoResponse\x12#\n\x06record\x18\x01 \x01(\x0b\x32\x13.echo.v1.EchoRecord\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xcd\x01\n\x0b\x45\x63hoService\x12\x45\n\nCreateEcho\x12\x1a.echo.v1.CreateEchoRequest\x1a\x1b.echo.v1.CreateEchoResponse\x12<\n\x07GetEcho\x12\x17.echo.v1.GetEchoRequest\x1a\x18.echo.v1.GetEchoResponse\x12\x39\n\x06Health\x12\x16.echo.v1.HealthRequest\x1a\x17.echo.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc.echo.v1.echo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECHORECORD']._serialized_start=35
  _globals['_ECHORECORD']._serialized_end=112
  _globals['_CREATEECHOREQUEST']._serialized_start=114
  _globals['_CREATEECHOREQUEST']._serialized_end=150
  _globals['_CREATEECHORESPONSE']._serialized_start=152
  _globals['_CREATEECHORESPONSE']._serialized_end=209
  _globals['_GETECHOREQUEST']._serialized_start=211
  _globals['_GETECHOREQUEST']._serialized_end=239
  _globals['_GETECHORESPONSE']._serialized_start=241
  _globals['_GETECHORESPONSE']._serialized_end=295
  _globals['_HEALTHREQUEST']._serialized_start=297
  _globals['_HEALTHREQUEST']._serialized_end=312
  _globals['_HEALTHRESPONSE']._serialized_start=314
  _globals['_HEALTHRESPONSE']._serialized_end=346
  _globals['_ECHOSERVICE']._serialized_start=349
  _globals['_ECHOSERVICE']._serialized_end=554
# @@protoc_insertion_point(module_scope)
