# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rpc.echo.v1 import echo_pb2 as rpc_dot_echo_dot_v1_dot_echo__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rpc/echo/v1/echo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EchoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEcho = channel.unary_unary(
                '/echo.v1.EchoService/CreateEcho',
                request_serializer=rpc_dot_echo_dot_v1_dot_echo__pb2.CreateEchoRequest.SerializeToString,
                response_deserializer=rpc_dot_echo_dot_v1_dot_echo__pb2.CreateEchoResponse.FromString,
                _registered_method=True)
        self.GetEcho = channel.unary_unary(
                '/echo.v1.EchoService/GetEcho',
                request_serializer=rpc_dot_echo_dot_v1_dot_echo__pb2.GetEchoRequest.SerializeToString,
                response_deserializer=rpc_dot_echo_dot_v1_dot_echo__pb2.GetEchoResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/echo.v1.EchoService/Health',
                request_serializer=rpc_dot_echo_dot_v1_dot_echo__pb2.HealthRequest.SerializeToString,
                response_deserializer=rpc_dot_echo_dot_v1_dot_echo__pb2.HealthResponse.FromString,
                _registered_method=True)


class EchoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateEcho(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEcho(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EchoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEcho': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEcho,
                    request_deserializer=rpc_dot_echo_dot_v1_dot_echo__pb2.CreateEchoRequest.FromString,
                    response_serializer=rpc_dot_echo_dot_v1_dot_echo__pb2.CreateEchoResponse.SerializeToString,
            ),
            'GetEcho': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEcho,
                    request_deserializer=rpc_dot_echo_dot_v1_dot_echo__pb2.GetEchoRequest.FromString,
                    response_serializer=rpc_dot_echo_dot_v1_dot_echo__pb2.GetEchoResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=rpc_dot_echo_dot_v1_dot_echo__pb2.HealthRequest.FromString,
                    response_serializer=rpc_dot_echo_dot_v1_dot_echo__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'echo.v1.EchoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('echo.v1.EchoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EchoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateEcho(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo.v1.EchoService/CreateEcho',
            rpc_dot_echo_dot_v1_dot_echo__pb2.CreateEchoRequest.SerializeToString,
            rpc_dot_echo_dot_v1_dot_echo__pb2.CreateEchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEcho(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo.v1.EchoService/GetEcho',
            rpc_dot_echo_dot_v1_dot_echo__pb2.GetEchoRequest.SerializeToString,
            rpc_dot_echo_dot_v1_dot_echo__pb2.GetEchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo.v1.EchoService/Health',
            rpc_dot_echo_dot_v1_dot_echo__pb2.HealthRequest.SerializeToString,
            rpc_dot_echo_dot_v1_dot_echo__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
