# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rpc.echo.v1 import echo_pb2 as rpc_dot_echo_dot_v1_dot_echo__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rpc/echo/v1/echo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExecutionRecordServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartService = channel.unary_unary(
                '/execution_record.v1.ExecutionRecordService/StartService',
                request_serializer=rpc_dot_echo_dot_v1_dot_echo__pb2.StartServiceRequest.SerializeToString,
                response_deserializer=rpc_dot_echo_dot_v1_dot_echo__pb2.StartServiceResponse.FromString,
                _registered_method=True)
        self.EndService = channel.unary_unary(
                '/execution_record.v1.ExecutionRecordService/EndService',
                request_serializer=rpc_dot_echo_dot_v1_dot_echo__pb2.EndServiceRequest.SerializeToString,
                response_deserializer=rpc_dot_echo_dot_v1_dot_echo__pb2.EndServiceResponse.FromString,
                _registered_method=True)
        self.QueryServiceRecords = channel.unary_unary(
                '/execution_record.v1.ExecutionRecordService/QueryServiceRecords',
                request_serializer=rpc_dot_echo_dot_v1_dot_echo__pb2.QueryServiceRecordsRequest.SerializeToString,
                response_deserializer=rpc_dot_echo_dot_v1_dot_echo__pb2.QueryServiceRecordsResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/execution_record.v1.ExecutionRecordService/Health',
                request_serializer=rpc_dot_echo_dot_v1_dot_echo__pb2.HealthRequest.SerializeToString,
                response_deserializer=rpc_dot_echo_dot_v1_dot_echo__pb2.HealthResponse.FromString,
                _registered_method=True)


class ExecutionRecordServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryServiceRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutionRecordServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartService': grpc.unary_unary_rpc_method_handler(
                    servicer.StartService,
                    request_deserializer=rpc_dot_echo_dot_v1_dot_echo__pb2.StartServiceRequest.FromString,
                    response_serializer=rpc_dot_echo_dot_v1_dot_echo__pb2.StartServiceResponse.SerializeToString,
            ),
            'EndService': grpc.unary_unary_rpc_method_handler(
                    servicer.EndService,
                    request_deserializer=rpc_dot_echo_dot_v1_dot_echo__pb2.EndServiceRequest.FromString,
                    response_serializer=rpc_dot_echo_dot_v1_dot_echo__pb2.EndServiceResponse.SerializeToString,
            ),
            'QueryServiceRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryServiceRecords,
                    request_deserializer=rpc_dot_echo_dot_v1_dot_echo__pb2.QueryServiceRecordsRequest.FromString,
                    response_serializer=rpc_dot_echo_dot_v1_dot_echo__pb2.QueryServiceRecordsResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=rpc_dot_echo_dot_v1_dot_echo__pb2.HealthRequest.FromString,
                    response_serializer=rpc_dot_echo_dot_v1_dot_echo__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'execution_record.v1.ExecutionRecordService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('execution_record.v1.ExecutionRecordService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExecutionRecordService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution_record.v1.ExecutionRecordService/StartService',
            rpc_dot_echo_dot_v1_dot_echo__pb2.StartServiceRequest.SerializeToString,
            rpc_dot_echo_dot_v1_dot_echo__pb2.StartServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution_record.v1.ExecutionRecordService/EndService',
            rpc_dot_echo_dot_v1_dot_echo__pb2.EndServiceRequest.SerializeToString,
            rpc_dot_echo_dot_v1_dot_echo__pb2.EndServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryServiceRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution_record.v1.ExecutionRecordService/QueryServiceRecords',
            rpc_dot_echo_dot_v1_dot_echo__pb2.QueryServiceRecordsRequest.SerializeToString,
            rpc_dot_echo_dot_v1_dot_echo__pb2.QueryServiceRecordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution_record.v1.ExecutionRecordService/Health',
            rpc_dot_echo_dot_v1_dot_echo__pb2.HealthRequest.SerializeToString,
            rpc_dot_echo_dot_v1_dot_echo__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
